title: Reece Lance
logo: "/images/logo.png?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Hello! I'm Reece, a Data Scientist currently pursuing an MSc in Data Science at the University of Essex.
  <h3>Skills</h3>
  <strong>Languages:</strong> Python, Java, R, SQL <\n>
  <strong>Tools:</strong> Power BI, Pandas, Scikit-learn, NumPy, Git
  <br><br>
  <a href="https://www.linkedin.com/in/reece-lance/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://github.com/reece-lance/">View My GitHub Profile</a>
  <br><br>
  Email me: Reecelance@gmail.com
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: G-4HYPS1HWDQ # your Google Analytics tracking ID here
